name: MERN App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js for the backend build
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      # Build and push the backend Docker image
      - name: Build and push backend Docker image
        env:
          DOCKER_USERNAME: "ayushgour"
          DOCKER_PASSWORD: "@123ayayay"
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t ayushgour/cicd-pipeline-trial:backend ./server
          docker push ayushgour/cicd-pipeline-trial:backend

      # Set up Docker for the frontend build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push the frontend Docker image
      - name: Build and push frontend Docker image
        env:
          DOCKER_USERNAME: "ayushgour"
          DOCKER_PASSWORD: "@123ayayay"
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t ayushgour/cicd-pipeline-trial:frontend ./client
          docker push ayushgour/cicd-pipeline-trial:frontend

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      # Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip
          sudo pip3 install docker-compose

      # Deploy the services using Docker Compose
      - name: Deploy services
        run: |
          docker-compose -f ../../docker-compose.yml up -d .
